apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-startup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nestjs-startup
  templete:
    metadata:
      name: nestjs-startup
    spec:
      container:
          image: image
        - name: nestjs-startup
      restartPolicy: Always
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: nestjs-startup-service
# spec:
#   type: ClusterIP
#   selector:
#     app: nestjs-startup
#   ports:
#     - port: 80
#       targetPort: 8080
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: nestjs-startup-service-node
# spec:
#   type: NodePort
#   selector:
#     app: nestjs-startup
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 8080
#       nodePort: 30000